[package]
name = "test_project"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.18.0"
scarb-version = "2.18.0"

[dependencies]
assert_macros = "2.18.0"
starknet = "2.18.0"
openzeppelin_macros = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v4.0.0-alpha.1" }
openzeppelin_access = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v4.0.0-alpha.1" }
openzeppelin_account = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v4.0.0-alpha.1" }
openzeppelin_finance = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v4.0.0-alpha.1" }
openzeppelin_interfaces = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v4.0.0-alpha.1" }
openzeppelin_governance = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v4.0.0-alpha.1" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v4.0.0-alpha.1" }
openzeppelin_security = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v4.0.0-alpha.1" }
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v4.0.0-alpha.1" }
openzeppelin_upgrades = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v4.0.0-alpha.1" }
openzeppelin_utils = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v4.0.0-alpha.1" }

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false
