name: Setup

runs:
  using: composite
  steps:
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: 20.x
        cache: yarn

    - name: Install dependencies
      run: yarn --frozen-lockfile --prefer-offline --network-concurrency 1
      shell: bash
