# coverage:
#   precision: 2
#   round: down
#   range: 70..100

#   status:
#     project:
#       default:
#         target: 85%
#         threshold: 2%
#     patch:
#       default:
#         target: auto
#         threshold: 1%

# flags:
#   stellar-backend-ai:
#     paths:
#       - "packages/ui/api/stellar/src/"
#     carryforward: true

#   stellar-backend-dev:
#     paths:
#       - "packages/ui/api/stellar/src/"
#     carryforward: true

# comment:
#   layout: "flags, diff, files"
#   require_changes: false
#   behavior: default

# ignore:
#   - "**/tests/*"
#   - "**/target/*"