[package]
name = "test_project"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.9.1"
scarb-version = "2.9.1"

[dependencies]
starknet = "2.9.1"
openzeppelin = "0.20.0"

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false
