[package]
name = "test_project"
version = "0.1.0"
edition = "2023_11"
cairo-version = "2.8.0"
scarb-version = "2.8.0"

[dependencies]
starknet = "2.8.0"
openzeppelin = "0.16.0"

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false
