[package]
name = "test_project"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.8.2"
scarb-version = "2.8.2"

[dependencies]
starknet = "2.8.2"
openzeppelin = "0.17.0"

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false
