import JSZip from 'jszip';
import type { Contract } from './contract';
import { HardhatZipGenerator } from './zip-hardhat';
import type { GenericOptions } from './build-generic';
import { printContract } from './print';
import { rewriteForTron } from './utils/transform-tron';

// Solidity version used by @openzeppelin/hardhat-tron and openzeppelin/tron-contracts.
// `tron-solc` 0.8.26 + cancun + viaIR is what the TRON Democritus hardfork
// (post-GreatVoyage 4.7) targets, and matches the README of OpenZeppelin/hardhat-tron.
const TRON_SOLIDITY_VERSION = '0.8.26';

class HardhatTronZipGenerator extends HardhatZipGenerator {
  protected getAdditionalHardhatImports(): string[] {
    // hardhat-tron does NOT use @nomicfoundation/hardhat-toolbox; the plugin
    // composes the smaller ethers + chai-matchers plugins that it actually needs.
    return ['@nomicfoundation/hardhat-ethers', '@nomicfoundation/hardhat-chai-matchers', '@openzeppelin/hardhat-tron'];
  }

  protected getHardhatConfigJsonString(): string {
    return `\
{
  solidity: {
    version: "${TRON_SOLIDITY_VERSION}",
    settings: {
      optimizer: { enabled: true, runs: 200 },
      evmVersion: 'cancun',
      viaIR: true,
      // Embed source as literal text in metadata so verification
      // services (Sourcify, etc.) can reconstruct it deterministically.
      metadata: { bytecodeHash: 'ipfs', useLiteralContent: true },
    },
  },
  tre: {
    autoStart: true,
    image: 'tronbox/tre:dev',
    compiler: { target: 'tron' },
  },
  defaultNetwork: 'tre',
  networks: {
    tre: {
      url: process.env.TRE_URL || 'http://127.0.0.1:9090/jsonrpc',
      tron: true,
      // Default well-known TRE dev key — fine for local tests, NEVER use on a real network.
      accounts: [process.env.TRE_PRIVATE_KEY || '0xdd23ca549a97cb330b011aebb674730df8b14acaee42d211ab45692699ab8ba5'],
    },
  },
}`;
  }

  protected getHardhatConfig(_upgradeable: boolean): string {
    // hardhat-tron-based projects use a non-upgradeable single config; the
    // `@openzeppelin/hardhat-upgrades` plugin is not used here. The hardhat
    // config is also emitted as a CommonJS .cjs file in the README sample,
    // but the TypeScript .ts variant works just as well with hardhat-tron.
    const additionalImports = this.getAdditionalHardhatImports();
    const importsSection = additionalImports.map(imp => `import "${imp}";`).join('\n');

    return `\
import { HardhatUserConfig } from "hardhat/config";
${importsSection}

const config: HardhatUserConfig = ${this.getHardhatConfigJsonString()};

export default config;
`;
  }

  protected async getPackageJson(c: Contract): Promise<unknown> {
    const { default: packageJson } = await import('./environments/hardhat/tron/package.json');
    packageJson.license = c.license;
    return packageJson;
  }

  protected async getPackageLock(_c: Contract): Promise<unknown> {
    // Not used. The TRON variant skips emitting a package-lock.json because
    // @openzeppelin/hardhat-tron and @openzeppelin/tron-contracts are not yet
    // published to the npm registry, so a lockfile would dangle. `npm install`
    // resolves the dependencies fresh when the packages are available.
    return undefined;
  }

  protected getReadmePrerequisitesSection(): string {
    return `\
## Prerequisites

Ensure you have the following installed:
- [Node.js 20+](https://nodejs.org/en/download/)
- [Docker](https://docs.docker.com/get-docker/) — the TRON Runtime Environment (\`tronbox/tre:dev\`) is spawned as a Docker container by \`@openzeppelin/hardhat-tron\`.

`;
  }

  protected getReadmeTestingEnvironmentSetupSection(): string {
    return `\
## TRON Runtime Environment

\`@openzeppelin/hardhat-tron\` spawns a local \`java-tron\` node (TRE) in Docker the first time you run \`npx hardhat test\` and tears it down on exit. No manual setup is required.

`;
  }

  protected getGitIgnoreHardhatIgnition(): string {
    // hardhat-ignition is not in scope for the TRON variant — we emit a plain
    // ethers script instead. Nothing to gitignore here.
    return '';
  }

  protected getPrintContract(c: Contract): string {
    return rewriteForTron(printContract(c));
  }

  protected getReadme(c: Contract): string {
    return `\
# Sample TRON Hardhat Project (${c.name})

This project demonstrates a TRON-targeted Hardhat use case using \`@openzeppelin/hardhat-tron\`. It comes with the \`${c.name}\` contract generated by [OpenZeppelin Wizard](https://wizard.openzeppelin.com/), a test for that contract, and a deploy script.

${this.getReadmePrerequisitesSection()}## Installing dependencies

\`\`\`
npm install
\`\`\`

${this.getReadmeTestingEnvironmentSetupSection()}## Testing the contract

\`\`\`
npm test
\`\`\`

## Deploying the contract

\`\`\`
npx hardhat run --network tre scripts/deploy.ts
\`\`\`

The default \`tre\` network in \`hardhat.config.ts\` points at a local TRON Runtime Environment (Docker container, spawned automatically by \`@openzeppelin/hardhat-tron\`). For Shasta, Nile, or mainnet, add a network entry and pass \`--network <name>\`.
`;
  }

  override async zipHardhat(c: Contract, opts?: GenericOptions): Promise<JSZip> {
    const zip = new JSZip();

    const packageJson = await this.getPackageJson(c);

    zip.file(`contracts/${c.name}.sol`, this.getPrintContract(c));
    zip.file('test/test.ts', this.getTest(c, opts));
    // No hardhat-ignition: the TRON dev flow is a plain ethers deploy script,
    // matching the @openzeppelin/hardhat-tron README.
    zip.file('scripts/deploy.ts', this.getScript(c));

    zip.file('.gitignore', this.getGitIgnore());
    zip.file('hardhat.config.ts', this.getHardhatConfig(c.upgradeable));
    zip.file('package.json', JSON.stringify(packageJson, null, 2));
    // package-lock.json is intentionally omitted; see getPackageLock().
    zip.file('README.md', this.getReadme(c));
    zip.file('tsconfig.json', this.getTsConfig());

    return zip;
  }
}

export async function zipHardhatTron(c: Contract, opts?: GenericOptions): Promise<JSZip> {
  return new HardhatTronZipGenerator().zipHardhat(c, opts);
}
