import JSZip from 'jszip';
import type { Contract } from './contract';
import { HardhatZipGenerator } from './zip-hardhat';
import type { GenericOptions } from './build-generic';
import { printContract } from './print';
import { tronPrintProfile, TRON_SOLIDITY_VERSION } from './utils/transform-tron';
import { hasUnsetInitArgs, isUUPS } from './utils/tron-upgradeable';

// `tron-solc` (TRON_SOLIDITY_VERSION) + cancun + viaIR is what the TRON
// Democritus hardfork (post-GreatVoyage 4.7) targets, and matches the README of
// OpenZeppelin/hardhat-tron. Sourced from the same constant as the printed pragma.

class HardhatTronZipGenerator extends HardhatZipGenerator {
  protected override getAdditionalHardhatImports(): string[] {
    // hardhat-tron does NOT use @nomicfoundation/hardhat-toolbox; the plugin
    // composes the smaller ethers + chai-matchers plugins that it actually needs.
    return ['@nomicfoundation/hardhat-ethers', '@nomicfoundation/hardhat-chai-matchers', '@openzeppelin/hardhat-tron'];
  }

  protected override getHardhatConfigJsonString(): string {
    return `\
{
  solidity: {
    version: "${TRON_SOLIDITY_VERSION}",
    settings: {
      optimizer: { enabled: true, runs: 200 },
      evmVersion: 'cancun',
      viaIR: true,
      // Embed source as literal text in metadata so verification
      // services (Sourcify, etc.) can reconstruct it deterministically.
      metadata: { bytecodeHash: 'ipfs', useLiteralContent: true },
    },
  },
  tre: {
    autoStart: true,
    image: 'tronbox/tre:dev',
    compiler: { target: 'tron' },
  },
  defaultNetwork: 'tre',
  networks: {
    tre: {
      url: process.env.TRE_URL || 'http://127.0.0.1:9090/jsonrpc',
      tron: true,
      // Default well-known TRE dev key — fine for local tests, NEVER use on a real network.
      accounts: [process.env.TRE_PRIVATE_KEY || '0xdd23ca549a97cb330b011aebb674730df8b14acaee42d211ab45692699ab8ba5'],
    },
  },
}`;
  }

  protected override getHardhatConfig(_upgradeable: boolean): string {
    // The TypeScript config works with both hardhat-tron plugins.
    const additionalImports = this.getAdditionalHardhatImports();
    if (_upgradeable) {
      additionalImports.push('@openzeppelin/hardhat-tron-upgrades');
    }
    const importsSection = additionalImports.map(imp => `import "${imp}";`).join('\n');

    return `\
import { HardhatUserConfig } from "hardhat/config";
${importsSection}

const config: HardhatUserConfig = ${this.getHardhatConfigJsonString()};

export default config;
`;
  }

  protected override async getPackageJson(c: Contract): Promise<unknown> {
    // The upgradeable manifest adds tron-contracts-upgradeable (the transpiled
    // `*Upgradeable` parents) and the upgrades plugin that validates the
    // implementation and deploys the proxy.
    const { default: packageJson } = c.upgradeable
      ? await import('./environments/hardhat/tron/upgradeable/package.json')
      : await import('./environments/hardhat/tron/package.json');
    return { ...packageJson, license: c.license };
  }

  protected override async getPackageLock(_c: Contract): Promise<unknown> {
    // Omitted: the sample resolves dependencies on first `npm install`.
    return undefined;
  }

  protected override getReadmePrerequisitesSection(): string {
    return `\
## Prerequisites

Ensure you have the following installed:
- [Node.js 20+](https://nodejs.org/en/download/)
- [Docker](https://docs.docker.com/get-docker/) — the TRON Runtime Environment (\`tronbox/tre:dev\`) is spawned as a Docker container by \`@openzeppelin/hardhat-tron\`.

`;
  }

  protected override getReadmeTestingEnvironmentSetupSection(): string {
    return `\
## TRON Runtime Environment

\`@openzeppelin/hardhat-tron\` spawns a local \`java-tron\` node (TRE) in Docker the first time you run \`npx hardhat test\` and tears it down on exit. No manual setup is required.

`;
  }

  protected override getGitIgnoreHardhatIgnition(): string {
    // hardhat-ignition is not in scope for the TRON variant — we emit a plain
    // ethers script instead. Nothing to gitignore here.
    return '';
  }

  protected override getPrintContract(c: Contract): string {
    return printContract(c, tronPrintProfile);
  }

  protected override getReadme(c: Contract): string {
    return `\
# Sample TRON Hardhat Project (${c.name})

This project demonstrates a TRON-targeted Hardhat use case using \`@openzeppelin/hardhat-tron\`. It comes with the \`${c.name}\` contract generated by [OpenZeppelin Wizard](https://wizard.openzeppelin.com/), a test for that contract, and a deploy script.

${this.getReadmePrerequisitesSection()}## Installing dependencies

\`\`\`
npm install
\`\`\`

${this.getReadmeTestingEnvironmentSetupSection()}## Testing the contract

\`\`\`
npm test
\`\`\`

## Deploying the contract

\`\`\`
npx hardhat run --network tre scripts/deploy.ts
\`\`\`

The default \`tre\` network in \`hardhat.config.ts\` points at a local TRON Runtime Environment (Docker container, spawned automatically by \`@openzeppelin/hardhat-tron\`). For Shasta, Nile, or mainnet, add a network entry and pass \`--network <name>\`.
${
  c.upgradeable
    ? `
> :information_source: This is an upgradeable contract. \`scripts/deploy.ts\` uses \`@openzeppelin/hardhat-tron-upgrades\` to validate the contract, deploy its implementation and proxy, and run \`initialize()\` atomically. Interact with the **proxy** address it prints. Keep the generated \`.openzeppelin\` network files for future upgrades.
`
    : ''
}`;
  }

  public override getHardhatPlugins(c: Contract): string[] {
    return c.upgradeable ? ['ethers', 'upgrades'] : ['ethers'];
  }

  protected override getScript(c: Contract): string {
    return c.upgradeable ? this.getUpgradeableScript(c) : super.getScript(c);
  }

  protected override getTest(c: Contract, opts?: GenericOptions): string {
    return c.upgradeable ? this.getUpgradeableTest(c, opts) : super.getTest(c, opts);
  }

  // Tests: address args default to a local signer. Scripts must not — see
  // `declareScriptInitArgs`. Non-address args are commented-out TODOs.
  private declareInitArgs(c: Contract): string[] {
    return c.constructorArgs.flatMap((arg, i) => {
      if (arg.type === 'address') {
        return [`  const ${arg.name} = signers[${i}].address;`];
      }
      return [`  // TODO: Set the initialize() argument "${arg.name}".`, `  // const ${arg.name} = ...;`];
    });
  }

  // Scripts: invalid sentinels so deploy throws until the user sets each address.
  private declareScriptInitArgs(c: Contract): string[] {
    return c.constructorArgs.flatMap(arg => {
      if (arg.type === 'address') {
        return [
          `  // TODO: Set an address for the initialize() argument "${arg.name}".`,
          `  const ${arg.name} = '<address>';`,
        ];
      }
      return [`  // TODO: Set the initialize() argument "${arg.name}".`, `  // const ${arg.name} = ...;`];
    });
  }

  private getUpgradeableScript(c: Contract): string {
    const gated = hasUnsetInitArgs(c);
    const g = gated ? '// ' : '';
    const uups = isUUPS(c);

    const argDecls = this.declareScriptInitArgs(c);
    const argList = c.constructorArgs.map(a => a.name).join(', ');
    const adminDecl = !uups
      ? `  // The transparent proxy's admin owner — it alone can upgrade the proxy.\n  // TODO: Set an address for proxyAdminOwner.\n  const proxyAdminOwner = '<address>';\n\n`
      : '';
    const deployOptions = uups ? `{ kind: "uups" }` : `{ kind: "transparent", initialOwner: proxyAdminOwner }`;

    return `\
import { ethers, upgrades } from "hardhat";

// Validates the implementation, deploys it behind a ${uups ? 'UUPS' : 'transparent'} proxy,
// and runs initialize() atomically.
async function main() {
  // Funds and activates the configured accounts in local TRE.
  await ethers.getSigners();

${argDecls.length > 0 ? argDecls.join('\n') + '\n\n' : ''}${adminDecl}${gated ? '  // TODO: Uncomment the lines below once the initialize() arguments above are set.\n' : ''}  ${g}const instance = await upgrades.deployProxy("${c.name}", [${argList}], ${deployOptions});
  ${g}await instance.waitForDeployment();
  ${g}console.log(\`${c.name} (proxy) deployed to \${await instance.getAddress()}\`);
}

// We recommend this pattern to be able to use async/await everywhere
// and properly handle errors.
main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
`;
  }

  private getUpgradeableTest(c: Contract, opts?: GenericOptions): string {
    const gated = hasUnsetInitArgs(c);
    const g = gated ? '// ' : '';
    const uups = isUUPS(c);

    const argDecls = this.declareInitArgs(c).map(line => '  ' + line);
    const argList = c.constructorArgs.map(a => a.name).join(', ');
    const deployOptions = uups ? `{ kind: "uups" }` : `{ kind: "transparent", initialOwner: signers[0].address }`;

    let assertion = '';
    if (opts !== undefined) {
      switch (opts.kind) {
        case 'ERC20':
        case 'ERC721':
          assertion = `    ${g}expect(await instance.name()).to.equal(${JSON.stringify(opts.name)});`;
          break;
        case 'ERC1155':
          assertion = `    ${g}expect(await instance.uri(0)).to.equal(${JSON.stringify(opts.uri)});`;
          break;
        default:
          break;
      }
    }

    return `\
import { expect } from "chai";
import { ethers, upgrades } from "hardhat";

describe("${c.name}", function () {
  it("deploys behind a proxy and initializes", async function () {
    // getSigners() also funds and activates the configured accounts in local TRE.
    const signers = await ethers.getSigners();

${argDecls.length > 0 ? argDecls.join('\n') + '\n' : ''}${gated ? '    // TODO: Uncomment the lines below once the initialize() arguments above are set.\n' : ''}    ${g}const instance = await upgrades.deployProxy("${c.name}", [${argList}], ${deployOptions});
    ${g}await instance.waitForDeployment();
${assertion ? assertion + '\n' : ''}  });
});
`;
  }

  override async zipHardhat(c: Contract, opts?: GenericOptions): Promise<JSZip> {
    const zip = new JSZip();

    const packageJson = await this.getPackageJson(c);

    zip.file(`contracts/${c.name}.sol`, this.getPrintContract(c));
    if (c.upgradeable) {
      // The upgrades plugin deploys these proxy artifacts after validating the implementation.
      zip.file(
        'contracts/ProxyImports.sol',
        `// SPDX-License-Identifier: MIT\npragma solidity ^${TRON_SOLIDITY_VERSION};\n\nimport "@openzeppelin/hardhat-tron-upgrades/contracts/Proxies.sol";\n`,
      );
    }
    zip.file('test/test.ts', this.getTest(c, opts));
    // No hardhat-ignition: the TRON dev flow is a plain ethers deploy script,
    // matching the @openzeppelin/hardhat-tron README.
    zip.file('scripts/deploy.ts', this.getScript(c));

    zip.file('.gitignore', this.getGitIgnore());
    zip.file('hardhat.config.ts', this.getHardhatConfig(c.upgradeable));
    zip.file('package.json', JSON.stringify(packageJson, null, 2));
    zip.file('README.md', this.getReadme(c));
    zip.file('tsconfig.json', this.getTsConfig());

    return zip;
  }
}

export async function zipHardhatTron(c: Contract, opts?: GenericOptions): Promise<JSZip> {
  return new HardhatTronZipGenerator().zipHardhat(c, opts);
}
