pub const README_MD: &str = r#"# Sample Rust Contract Environment

This project demonstrates a basic Rust contract environment use case. It comes with a contract generated by [OpenZeppelin Wizard](https://wizard.openzeppelin.com/) and a test for that contract. Make sure you have the required dependencies and keep building!

## Go further

Continue your development journey with [Stellar CLI](https://github.com/stellar/stellar-cli).

## Installing dependencies

- See [Rust and Stellar installation guide](https://developers.stellar.org/docs/build/smart-contracts/getting-started/setup).
- See [Git installation guide](https://github.com/git-guides/install-git).
"#;

pub const CREATE_RUST_LIB_FILE: &str = r#"#![no_std]
use soroban_sdk as _;
pub mod contract;
"#;
