[package]
name = "stellar-api"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4.11.0"
actix-cors = "0.7.1"
actix-governor = "0.8"
env_logger = "0.11.8"
dotenvy = "0.15.7"
log = "0.4.28"
zip = "^5.1.1"
walkdir = "^2.5.0"
tempfile = "^3.21.0"
globset = "^0.4.16"
libc = "^0.2.175"

[package.metadata.tools]
stellar_cli = "23.0.1"
stellar_scaffold_cli = "0.0.8"

[[bin]]
name = "stellar-api"
path = "src/main.rs"
