# Basic formatting
max_width = 100
tab_spaces = 4
hard_tabs = false
edition = "2024"

# Code organization
reorder_imports = true
reorder_modules = true

# Formatting preferences
merge_derives = true

# Function and control flow formatting
fn_params_layout = "Tall"

# Code style preferences
use_try_shorthand = true
use_field_init_shorthand = true
